### ISSUE TITLE
yamlのスニペット一覧からスニペット用コードをロードする

### ISSUE THREAD

**Issue by wotsushi** [wotsushi/compro-library#3]
## 概要

スニペット用コード一覧をyaml形式のファイルで記述し、それをもとにスニペット生成できるようにする。

## 仕様
- `snippets.yml` にスニペット用コード一覧を記述する。
- スニペット用コードは `lib/パッケージ名/スニペット名` に格納されているものとする。
- yamlは以下の形式にしたがう。

```yml
- package: パッケージ名
  snippets:
    - name: スニペット名
...
```

## ステータス
- [x] テスト用のスニペットコードファイルを格納
- [x] yamlの作成
- [x] yamlのdeserialize方法調査
- [x] 実装
- [x] 動作確認
